title: 4th Workshop on Intelligent and Automated <br /> Waterway Transportation
description: IEEE ITSC, Gold Coast, Australia, November 18, 2024 \n **👉 [Call for Contributions](https://docs.google.com/forms/d/e/1FAIpQLSegqE_srBeCVRJyyzYTrg0mcZAQsLEN1gQThHxMP2hL7_fXgQ/viewform?usp=header)**

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

github:
  is_project_page: false
