title: 4th Workshop on Intelligent and Automated <br /> Waterway Transportation
description: IEEE ITSC, Gold Coast, Australia, November 18, 2025

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

github:
  is_project_page: false
