title: 3rd Workshop on Intelligent and Automated <br /> Waterway Transportation
description: IEEE ITSC, Edmonton, Canada, September 24, 2024

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

github:
  is_project_page: false
